//! This module handles construction of the rendered nix code as the output

mod nix_escaper;

pub use nix_escaper::NixEscaper;

use crate::{Options, error::Result};
use askama::Template;
use std::{any::Any, collections::HashMap};

use crate::Package;

/// # Nix Expression
///
/// A chunk of nix code to be written to stdout or a file
#[derive(Template)]
#[template(path = "output.nix_template")]
pub struct NixExpression {
    packages: Vec<Package>,
}

impl NixExpression {
    /// # New Nix Expression
    ///
    /// Produce a new, ready to render, nix expression from a package list
    pub fn new(packages: Vec<Package>) -> Result<Self> {
        Ok(Self { packages })
    }

    /// # Render with options
    ///
    /// Renders a `NixExpression` with the supplied config options
    pub fn render_with_options(self, options: Options) -> Result<String> {
        let mut values: HashMap<&str, Box<dyn Any>> = HashMap::new();
        values.insert("options", Box::new(options));

        Ok(self.render_with_values(&values)?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::package::Fetcher;
    use bun2nix_core::manifest::meta::VersionMeta;
    use std::collections::BTreeMap;

    fn opts() -> Options {
        Options {
            copy_prefix: "./".to_string(),
        }
    }

    fn render(packages: Vec<Package>) -> String {
        NixExpression::new(packages)
            .unwrap()
            .render_with_options(opts())
            .unwrap()
    }

    /// A package with an attached manifest must:
    /// (a) emit the manifest's `tarball_url` as the entry `url` (not inference),
    /// (b) render a `manifest = { ... }` block with `tarballUrl`, `dependencies`,
    ///     and `optionalPeers`, and
    /// (c) NOT emit an `integrity` key (it is reused downstream from `hash`).
    #[test]
    fn renders_manifest_block_and_prefers_tarball_url() {
        let inferred = "https://registry.npmjs.org/foo/-/foo-1.0.0.tgz";
        let manifest_url = "https://registry.npmjs.org/foo/-/foo-1.0.0-DIFFERENT.tgz";

        let fetcher = Fetcher::FetchUrl {
            url: inferred.to_string(),
            hash: "sha512-AAAA".to_string(),
            name: None,
        };

        let vm = VersionMeta {
            version: "1.0.0".to_string(),
            tarball_url: manifest_url.to_string(),
            integrity: "sha512-SHOULD_NOT_APPEAR".to_string(),
            dependencies: BTreeMap::from([("bar".to_string(), "^1.0.0".to_string())]),
            peer_dependencies: BTreeMap::new(),
            optional_dependencies: BTreeMap::new(),
            optional_peers: vec!["baz".to_string()],
            bin: BTreeMap::new(),
            os: vec![],
            cpu: vec![],
            has_install_script: false,
        };

        let pkg = Package::new("foo@1.0.0".to_string(), fetcher).with_manifest(vm);
        let out = render(vec![pkg]);

        // (a) manifest tarball_url wins over inference
        assert!(
            out.contains(manifest_url),
            "expected manifest tarball_url in output:\n{out}"
        );
        assert!(
            !out.contains(inferred),
            "inferred url should have been replaced:\n{out}"
        );

        // (b) manifest block present with required keys
        assert!(
            out.contains("manifest = {"),
            "missing manifest block:\n{out}"
        );
        assert!(out.contains("tarballUrl ="), "missing tarballUrl:\n{out}");
        assert!(
            out.contains("dependencies ="),
            "missing dependencies:\n{out}"
        );
        assert!(
            out.contains("optionalPeers ="),
            "missing optionalPeers:\n{out}"
        );
        assert!(
            out.contains("\"bar\" = \"^1.0.0\""),
            "missing dep entry:\n{out}"
        );

        // (c) no integrity key (reused from entry hash downstream)
        assert!(
            !out.contains("integrity"),
            "integrity must not be emitted:\n{out}"
        );
        assert!(
            !out.contains("SHOULD_NOT_APPEAR"),
            "integrity value leaked:\n{out}"
        );
    }

    /// A package with no manifest must render byte-identically to the
    /// pre-change output (backward compatibility / offline fallback).
    #[test]
    fn manifest_none_renders_identically_to_before() {
        let fetcher = Fetcher::FetchUrl {
            url: "https://registry.npmjs.org/foo/-/foo-1.0.0.tgz".to_string(),
            hash: "sha512-AAAA".to_string(),
            name: None,
        };
        let pkg = Package::new("foo@1.0.0".to_string(), fetcher);
        let out = render(vec![pkg]);

        let expected = "# Autogenerated by `bun2nix`, editing manually is not recommended\n\
#\n\
# Set of Bun packages to install\n\
#\n\
# Consume this with `fetchBunDeps` (recommended)\n\
# or `pkgs.callPackage` if you wish to handle\n\
# it manually.\n\
{\n  \
copyPathToStore,\n  \
fetchFromGitHub,\n  \
fetchgit,\n  \
fetchurl,\n  \
...\n\
}:\n\
{\n  \
\"foo@1.0.0\" = fetchurl {\n    \
url = \"https://registry.npmjs.org/foo/-/foo-1.0.0.tgz\";\n    \
hash = \"sha512-AAAA\";\n  \
};\n\
}";

        assert_eq!(out, expected);
    }

    /// Nix string values must be escaped so the output is always valid Nix.
    #[test]
    fn escapes_nix_special_characters_in_values() {
        let fetcher = Fetcher::FetchUrl {
            url: "https://registry.npmjs.org/foo/-/foo-1.0.0.tgz".to_string(),
            hash: "sha512-AAAA".to_string(),
            name: None,
        };
        let vm = VersionMeta {
            version: "1.0.0".to_string(),
            tarball_url: "https://registry.npmjs.org/foo/-/foo-1.0.0.tgz".to_string(),
            integrity: String::new(),
            // A dependency range containing characters that are special in Nix.
            dependencies: BTreeMap::from([(
                "weird".to_string(),
                "back\\slash \"quote\" ${interp}".to_string(),
            )]),
            peer_dependencies: BTreeMap::new(),
            optional_dependencies: BTreeMap::new(),
            optional_peers: vec![],
            bin: BTreeMap::new(),
            os: vec![],
            cpu: vec![],
            has_install_script: false,
        };
        let pkg = Package::new("foo@1.0.0".to_string(), fetcher).with_manifest(vm);
        let out = render(vec![pkg]);

        assert!(
            out.contains("back\\\\slash \\\"quote\\\" \\${interp}"),
            "special characters not escaped:\n{out}"
        );
    }

    /// A package with a non-default registry renders `registry = "...";`
    /// inside its manifest block; a default-registry package must not.
    #[test]
    fn renders_registry_attr_for_non_default_entries() {
        let url = "https://registry.npmmirror.com/react/-/react-19.2.7.tgz";
        let fetcher = Fetcher::FetchUrl {
            url: url.to_string(),
            hash: "sha512-AAAA".to_string(),
            name: Some("react-19.2.7.tgz".to_string()),
        };
        let vm = VersionMeta {
            version: "19.2.7".to_string(),
            tarball_url: url.to_string(),
            integrity: String::new(),
            dependencies: BTreeMap::new(),
            peer_dependencies: BTreeMap::new(),
            optional_dependencies: BTreeMap::new(),
            optional_peers: vec![],
            bin: BTreeMap::new(),
            os: vec![],
            cpu: vec![],
            has_install_script: false,
        };
        let mut pkg = Package::new("react@19.2.7".to_string(), fetcher).with_manifest(vm);
        pkg.registry = Some("https://registry.npmmirror.com".to_string());
        let out = render(vec![pkg]);

        assert!(
            out.contains("registry = \"https://registry.npmmirror.com\";"),
            "missing registry attr:\n{out}"
        );
    }

    #[test]
    fn no_registry_attr_for_default_entries() {
        let fetcher = Fetcher::FetchUrl {
            url: "https://registry.npmjs.org/foo/-/foo-1.0.0.tgz".to_string(),
            hash: "sha512-AAAA".to_string(),
            name: None,
        };
        let vm = VersionMeta {
            version: "1.0.0".to_string(),
            tarball_url: "https://registry.npmjs.org/foo/-/foo-1.0.0.tgz".to_string(),
            integrity: String::new(),
            dependencies: BTreeMap::new(),
            peer_dependencies: BTreeMap::new(),
            optional_dependencies: BTreeMap::new(),
            optional_peers: vec![],
            bin: BTreeMap::new(),
            os: vec![],
            cpu: vec![],
            has_install_script: false,
        };
        let pkg = Package::new("foo@1.0.0".to_string(), fetcher).with_manifest(vm);
        let out = render(vec![pkg]);

        assert!(
            !out.contains("registry ="),
            "unexpected registry attr:\n{out}"
        );
    }
}
