[package]
name = "bun2nix"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonc-parser = { version = "0.26.2", features = ["serde"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
thiserror = "2.0.11"
clap = { version = "4.5.31", features = ["derive"] }
sha2 = "0.10.8"
reqwest = "0.12.12"
futures = "0.3.31"
tokio = { version = "1.42.0", features = ["rt", "macros", "rt-multi-thread"] }
base64 = "0.22.1"
