# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  fetchurl,
  ...
}:
{
  "react-dom@19.2.8" =
    fetchurl {
      url = "https://registry.npmmirror.com/react-dom/-/react-dom-19.2.8.tgz";
      hash = "sha512-rVprimfGBG3DR+Tq0IQG2DT5PxKth1WIGDmj5yPmlzr4YBe7uyE+Du4oVqTDXZSHGGGXRtTJEGSSePyQCMBglQ==";
      name = "react-dom-19.2.8.tgz";
    }
    // {
      manifest = {
        registry = "https://registry.npmmirror.com";
        tarballUrl = "https://registry.npmmirror.com/react-dom/-/react-dom-19.2.8.tgz";
        dependencies = {
          "scheduler" = "^0.27.0";
        };
        peerDependencies = {
          "react" = "^19.2.8";
        };
        optionalDependencies = { };
        optionalPeers = [ ];
        bin = { };
        os = [ ];
        cpu = [ ];
        hasInstallScript = false;
      };
    };
  "react@19.2.8" =
    fetchurl {
      url = "https://registry.npmmirror.com/react/-/react-19.2.8.tgz";
      hash = "sha512-PWaYA1L/q9u2u7xYQi+Y3L3Yfnie7XyLeaJICV1MGD6LprsBxcAqGjYyr0eY3p+QdsA+x/Irkt4Qif8D63+Sbw==";
      name = "react-19.2.8.tgz";
    }
    // {
      manifest = {
        registry = "https://registry.npmmirror.com";
        tarballUrl = "https://registry.npmmirror.com/react/-/react-19.2.8.tgz";
        dependencies = { };
        peerDependencies = { };
        optionalDependencies = { };
        optionalPeers = [ ];
        bin = { };
        os = [ ];
        cpu = [ ];
        hasInstallScript = false;
      };
    };
  "scheduler@0.27.0" =
    fetchurl {
      url = "https://registry.npmmirror.com/scheduler/-/scheduler-0.27.0.tgz";
      hash = "sha512-eNv+WrVbKu1f3vbYJT/xtiF5syA5HPIMtf9IgY/nKg0sWqzAUEvqY/xm7OcZc/qafLx/iO9FgOmeSAp4v5ti/Q==";
      name = "scheduler-0.27.0.tgz";
    }
    // {
      manifest = {
        registry = "https://registry.npmmirror.com";
        tarballUrl = "https://registry.npmmirror.com/scheduler/-/scheduler-0.27.0.tgz";
        dependencies = { };
        peerDependencies = { };
        optionalDependencies = { };
        optionalPeers = [ ];
        bin = { };
        os = [ ];
        cpu = [ ];
        hasInstallScript = false;
      };
    };
}
