# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  fetchurl,
  ...
}:
{
  "react-dom@19.2.7" =
    fetchurl {
      url = "https://registry.npmjs.org/react-dom/-/react-dom-19.2.7.tgz";
      hash = "sha512-t0BRVXvbiE/o20Hfw669rLbMCDWtYZLvmJigy2f0MxsXF+71pxhR3xOkspmsO8h3ZlNzyibAmtCa3l4lYKk6gQ==";
    }
    // {
      manifest = {
        tarballUrl = "https://registry.npmjs.org/react-dom/-/react-dom-19.2.7.tgz";
        dependencies = {
          "scheduler" = "^0.27.0";
        };
        peerDependencies = {
          "react" = "^19.2.7";
        };
        optionalDependencies = { };
        optionalPeers = [ ];
        bin = { };
        os = [ ];
        cpu = [ ];
        hasInstallScript = false;
      };
    };
  "react@19.2.7" =
    fetchurl {
      url = "https://registry.npmjs.org/react/-/react-19.2.7.tgz";
      hash = "sha512-HNe9WslTbXmFK8o8cmwgAeJFSBvt1bPdHCVKtaaV+WlAN36mpT4hcRpwbf3fY56ar2oIXzsBpOAiIRHAdY0OlQ==";
    }
    // {
      manifest = {
        tarballUrl = "https://registry.npmjs.org/react/-/react-19.2.7.tgz";
        dependencies = { };
        peerDependencies = { };
        optionalDependencies = { };
        optionalPeers = [ ];
        bin = { };
        os = [ ];
        cpu = [ ];
        hasInstallScript = false;
      };
    };
  "scheduler@0.27.0" =
    fetchurl {
      url = "https://registry.npmjs.org/scheduler/-/scheduler-0.27.0.tgz";
      hash = "sha512-eNv+WrVbKu1f3vbYJT/xtiF5syA5HPIMtf9IgY/nKg0sWqzAUEvqY/xm7OcZc/qafLx/iO9FgOmeSAp4v5ti/Q==";
    }
    // {
      manifest = {
        tarballUrl = "https://registry.npmjs.org/scheduler/-/scheduler-0.27.0.tgz";
        dependencies = { };
        peerDependencies = { };
        optionalDependencies = { };
        optionalPeers = [ ];
        bin = { };
        os = [ ];
        cpu = [ ];
        hasInstallScript = false;
      };
    };
}
